name: Sample
description: Testing it
inputs:
  variable:
    description: A string
    required: false
runs:
  using: composite
  steps:
    - name: Run script
      shell: bash
      if: ${{ inputs.variable }} != ''
      run: echo "Variable value is ${{ inputs.variable }}"
