name: Sample
description: Testing it
inputs:
  variable:
    type: string
    description: A string
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: Run script
      shell: bash
      if: github.events.inputs.variable != ""
      run: echo "Variable value is ${{ inputs.variable }}"
