name: Sample
description: Testing it
inputs:
  variable:
    description: A string
    required: false
runs:
  using: composite
  steps:
    - name: Run script
      shell: bash
      run: |
        if [ -n "${{ inputs.variable }}" ]; then
          echo "Variable value is ${{ inputs.variable }}"
        fi
