# Trigget github actions
name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
      - name: Run it
        uses: ./.github/actions/sample
        with:
          variable: foo
